package Views;
import javax.swing.JFrame;
import javax.swing.JOptionPane;
/**
 *
 * @author Ulises Gachuz Davila
 */
public class Menu extends JFrame {

    /**
     * Creates new form Menu
     */
    
    public static String cantidad = "";
    
    public Menu() {
        initComponents();
        setTitle("Menú principal");
        setLocationRelativeTo(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPnlMenu = new javax.swing.JPanel();
        jLblSeleccion = new javax.swing.JLabel();
        jCBxTipoConversion = new javax.swing.JComboBox<>();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPnlMenu.setBackground(new java.awt.Color(228, 233, 178));

        jLblSeleccion.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N
        jLblSeleccion.setText("Seleccione una opción de conversión:");

        jCBxTipoConversion.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N
        jCBxTipoConversion.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Conversor de moneda", "Conversor de temperatura" }));
        jCBxTipoConversion.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jCBxTipoConversionActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPnlMenuLayout = new javax.swing.GroupLayout(jPnlMenu);
        jPnlMenu.setLayout(jPnlMenuLayout);
        jPnlMenuLayout.setHorizontalGroup(
            jPnlMenuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPnlMenuLayout.createSequentialGroup()
                .addGap(21, 21, 21)
                .addGroup(jPnlMenuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jCBxTipoConversion, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPnlMenuLayout.createSequentialGroup()
                        .addGap(45, 45, 45)
                        .addComponent(jLblSeleccion, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGap(50, 50, 50)))
                .addGap(15, 15, 15))
        );
        jPnlMenuLayout.setVerticalGroup(
            jPnlMenuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPnlMenuLayout.createSequentialGroup()
                .addGap(15, 15, 15)
                .addComponent(jLblSeleccion)
                .addGap(18, 18, 18)
                .addComponent(jCBxTipoConversion, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(119, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPnlMenu, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPnlMenu, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jCBxTipoConversionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jCBxTipoConversionActionPerformed
        int opcion = jCBxTipoConversion.getSelectedIndex();
        ConversorMoneda moneda = new ConversorMoneda();
        ConversorTemperatura temperatura = new ConversorTemperatura();
        switch(opcion){
            case 0 -> {
                // Convertir monedas
                this.setVisible(false);
                cantidad = JOptionPane.showInputDialog("Ingrese la cantidad de dinero que desea convertir: ");
                if (cantidad == null || cantidad.trim().isEmpty()) {
                    this.setVisible(true);
                }else{
                    moneda.setVisible(true);
                }
            }

            case 1 -> {
                // Convertir temperatura
                this.setVisible(false);
                cantidad = JOptionPane.showInputDialog("Ingrese la cantidad que desea convertir: ");
                System.out.println("Mensaje:" + cantidad);
                if (cantidad == null || cantidad.trim().isEmpty()) {
                    this.setVisible(true);
                }else{
                    temperatura.setVisible(true);
                }
            }
            
        }
        // Aqui va la ventana de conversor de temperatura
    }//GEN-LAST:event_jCBxTipoConversionActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Menu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Menu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Menu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Menu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Menu().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox<String> jCBxTipoConversion;
    private javax.swing.JLabel jLblSeleccion;
    private javax.swing.JPanel jPnlMenu;
    // End of variables declaration//GEN-END:variables
}
